(()=>{
 const dialog=document.getElementById('orbit-dialog'),canvas=document.getElementById('orbit-canvas'),ctx=canvas.getContext('2d');
 const state={yaw:.35,pitch:-.27,phase:0,paused:reduced,speed:1,coverage:true,previous:0,raf:0,drag:null,opener:null};
 const deMode=()=>document.documentElement.lang==='de';
 const closeBtn=document.getElementById('orbit-close'),pauseBtn=document.getElementById('orbit-pause'),speedBtn=document.getElementById('orbit-speed'),coverageBtn=document.getElementById('orbit-coverage');
 const keyboardClick=(el,fn)=>{el.addEventListener('click',fn);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn(e)}})};
 function refresh(){const german=deMode();pauseBtn.textContent=german?(state.paused?'Starten':'Pause'):(state.paused?'Play':'Pause');pauseBtn.setAttribute('aria-pressed',String(state.paused));coverageBtn.textContent=german?(state.coverage?'Abdeckung an':'Abdeckung aus'):(state.coverage?'Coverage on':'Coverage off');coverageBtn.setAttribute('aria-pressed',String(state.coverage));speedBtn.setAttribute('aria-label',german?'Animationsgeschwindigkeit ändern':'Change animation speed');canvas.setAttribute('aria-label',german?'Simulierte Satellitenkonstellation, mit Pfeiltasten drehbar':'Simulated satellite constellation, use arrow keys to rotate');document.getElementById('network').setAttribute('aria-label',german?'Einen Impuls durch das neuronale Netz senden':'Send a pulse through the neural network');document.getElementById('coverage').setAttribute('aria-label',german?'Orbit-Simulation vergrößern':'Expand the orbital simulation');document.getElementById('inference-flow').setAttribute('aria-label',german?'Eine beispielhafte Vorhersage animieren':'Animate an example prediction request')}
 window.refreshVisualLabels=refresh;refresh();
 function open(e){state.opener=e?.currentTarget||document.activeElement;state.previous=0;vizState.exploring=true;if(reduced)render(0);dialog.showModal();document.body.classList.add('orbit-open');refresh();draw(performance.now());state.raf=requestAnimationFrame(tick)}
 keyboardClick(document.getElementById('globe'),open);keyboardClick(document.getElementById('coverage'),open);
 function close(){dialog.close()}
 closeBtn.addEventListener('click',close);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
 dialog.addEventListener('close',()=>{cancelAnimationFrame(state.raf);state.raf=0;state.previous=0;vizState.exploring=false;if(reduced)render(0);document.body.classList.remove('orbit-open');if(state.opener?.focus)state.opener.focus()});
 pauseBtn.addEventListener('click',()=>{state.paused=!state.paused;refresh()});speedBtn.addEventListener('click',()=>{state.speed=state.speed===1?3:1;speedBtn.textContent=state.speed+'×';speedBtn.setAttribute('aria-pressed',String(state.speed===3))});coverageBtn.addEventListener('click',()=>{state.coverage=!state.coverage;refresh()});document.getElementById('orbit-reset').addEventListener('click',()=>{state.yaw=.35;state.pitch=-.27;state.phase=0;state.speed=1;speedBtn.textContent='1×';speedBtn.setAttribute('aria-pressed','false')});
 canvas.addEventListener('pointerdown',e=>{state.drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;state.yaw+=(e.clientX-state.drag.x)*.008;state.pitch=Math.max(-1.3,Math.min(1.3,state.pitch+(e.clientY-state.drag.y)*.008));state.drag.x=e.clientX;state.drag.y=e.clientY});const stop=()=>state.drag=null;canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);canvas.addEventListener('lostpointercapture',stop);canvas.addEventListener('keydown',e=>{const actions={ArrowLeft:()=>state.yaw-=.12,ArrowRight:()=>state.yaw+=.12,ArrowUp:()=>state.pitch=Math.max(-1.3,state.pitch-.12),ArrowDown:()=>state.pitch=Math.min(1.3,state.pitch+.12)};if(actions[e.key]){e.preventDefault();actions[e.key]()}});
 function rotate(v){const y=state.yaw,p=state.pitch,a=v[0]*Math.cos(y)+v[2]*Math.sin(y),b=v[2]*Math.cos(y)-v[0]*Math.sin(y);return[a,v[1]*Math.cos(p)-b*Math.sin(p),v[1]*Math.sin(p)+b*Math.cos(p)]}
 function orbit(a,plane,r=1.3){const inc=[.35,1.08,1.48][plane],head=plane*.92,v=[r*Math.cos(a),r*Math.sin(a)*Math.cos(inc),r*Math.sin(a)*Math.sin(inc)];return[v[0]*Math.cos(head)-v[1]*Math.sin(head),v[0]*Math.sin(head)+v[1]*Math.cos(head),v[2]]}
 function draw(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2),w=rect.width,h=rect.height;if(!w||!h)return;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const radius=Math.min(w*.3,h*.31),cx=w/2,cy=h/2+8;const project=v=>{const q=rotate(v),scale=radius*4/(4-q[2]);return{x:cx+q[0]*scale,y:cy+q[1]*scale,z:q[2]}};
  const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,radius*1.7);glow.addColorStop(0,'#53dfce13');glow.addColorStop(1,'#53dfce00');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
  for(let i=0;i<65;i++){const x=((i*127.13)%997)/997*w,y=((i*83.77)%991)/991*h;ctx.fillStyle=i%4?'#56798744':'#9ac9ce77';ctx.fillRect(x,y,1,1)}
  const line=(points,color,frontOnly=false,width=1)=>{ctx.lineWidth=width;for(let i=1;i<points.length;i++){const a=project(points[i-1]),b=project(points[i]);if(frontOnly&&a.z<0&&b.z<0)continue;ctx.strokeStyle=color;ctx.globalAlpha=(a.z<0&&b.z<0)?.28:1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.globalAlpha=1};
  const samples=fn=>Array.from({length:97},(_,j)=>fn(j/96*Math.PI*2));
  for(let lat=-Math.PI/2+.2;lat<Math.PI/2;lat+=.21)line(samples(a=>[Math.cos(lat)*Math.cos(a),Math.sin(lat),Math.cos(lat)*Math.sin(a)]),'#377d8655');
  for(let lon=0;lon<Math.PI*2;lon+=Math.PI/10)line(samples(a=>[Math.cos(a)*Math.cos(lon),Math.sin(a),Math.cos(a)*Math.sin(lon)]),'#377d8655');
  for(let plane=0;plane<3;plane++)line(samples(a=>orbit(a,plane)),plane===1?'#6be5d266':'#84b0dd55');
  const sats=[];for(let plane=0;plane<3;plane++)for(let j=0;j<4;j++){const angle=state.phase*(1+plane*.14)+j*Math.PI/2+plane*.37;sats.push({v:orbit(angle,plane),plane,angle})}sats.sort((a,b)=>project(a.v).z-project(b.v).z);
  for(const sat of sats){const point=project(sat.v),color=sat.plane===1?'#6be5d2':'#a4c9fa';if(state.coverage){const g=sat.v.map(x=>x/1.3);if(rotate(g)[2]>0){line([sat.v,g],'#6be5d24d',false,1);const tangent=[-g[1],g[0],0],mag=Math.hypot(...tangent)||1,u=tangent.map(a=>a/mag),v=[g[1]*u[2]-g[2]*u[1],g[2]*u[0]-g[0]*u[2],g[0]*u[1]-g[1]*u[0]];line(samples(a=>g.map((n,k)=>n*Math.cos(.18)+Math.sin(.18)*(u[k]*Math.cos(a)+v[k]*Math.sin(a)))),'#6be5d25f',true)}}
   const trail=Array.from({length:25},(_,j)=>orbit(sat.angle-.5+j/24*.5,sat.plane));line(trail,color+'77',false,1.7);ctx.globalAlpha=point.z<0?.5:1;ctx.shadowColor=color;ctx.shadowBlur=14;ctx.fillStyle=color;ctx.beginPath();ctx.arc(point.x,point.y,3.2,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=color+'55';ctx.beginPath();ctx.arc(point.x,point.y,7,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}
  document.getElementById('utc-clock').textContent=new Date().toISOString().slice(11,19)+' UTC';document.getElementById('utc-clock').setAttribute('datetime',new Date().toISOString())
 }
 function tick(ms){if(!dialog.open)return;const dt=state.previous?Math.min((ms-state.previous)/1000,.05):0;state.previous=ms;if(!state.paused)state.phase+=dt*.18*state.speed;draw(ms);state.raf=requestAnimationFrame(tick)}
 const neuralEl=document.getElementById('network');keyboardClick(neuralEl,()=>{window.neuralBurst=performance.now();if(reduced)neural(performance.now())});
 const signal=document.getElementById('signal');signal.addEventListener('click',()=>window.signalKick=performance.now());signal.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')window.signalKick=performance.now()});
 const flow=document.getElementById('inference-flow');let flowTimer;keyboardClick(flow,()=>{clearTimeout(flowTimer);flow.classList.remove('running');void flow.offsetWidth;flow.classList.add('running');flowTimer=setTimeout(()=>flow.classList.remove('running'),4000)});
 const portrait=document.querySelector('.portrait-frame');if(!reduced&&matchMedia('(pointer: fine)').matches){portrait.addEventListener('pointermove',e=>{const r=portrait.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;portrait.style.setProperty('--tilt-x',((.5-y)*5)+'deg');portrait.style.setProperty('--tilt-y',((x-.5)*5)+'deg');portrait.style.setProperty('--shine-x',x*100+'%');portrait.style.setProperty('--shine-y',y*100+'%')});portrait.addEventListener('pointerleave',()=>{portrait.style.setProperty('--tilt-x','0deg');portrait.style.setProperty('--tilt-y','0deg')})}
})();
